language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- curl https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz > /tmp/google-cloud-sdk.tar.gz
- tar -C /tmp -xf /tmp/google-cloud-sdk.tar.gz && bash /tmp/google-cloud-sdk/install.sh
- gcloud auth activate-service-account --key-file=gcpkey.json
- gsutil cp -r build/. gs://dev.bykovsky.com
before_install:
- openssl aes-256-cbc -K $encrypted_fffda0c215cc_key -iv $encrypted_fffda0c215cc_iv
  -in gcpkey.json.enc -out gcpkey.json -d
