language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
- curl https://sdk.cloud.google.com > install.sh
- bash install.sh --disable-prompts
- gcloud auth activate-service-account --key-file=gcpkey.json
- gsutil cp -r build/. gs://dev.bykovsky.com
before_install:
- openssl aes-256-cbc -K $encrypted_fffda0c215cc_key -iv $encrypted_fffda0c215cc_iv
  -in gcpkey.json.enc -out gcpkey.json -d
