language: ruby
services:
  - docker
script:
- docker build .
before_install:
- openssl aes-256-cbc -K $encrypted_fffda0c215cc_key -iv $encrypted_fffda0c215cc_iv
  -in gcpkey.json.enc -out gcpkey.json -d
